import { Injectable } from '@nestjs/common';
import { PrismaService } from '@app/shared';
import * as ExcelJS from 'exceljs';
import { Response } from 'express';

@Injectable()
export class ReportingService {
  constructor(private prisma: PrismaService) {}

  async generateExcelReport(userId: string, res: Response) {
    const user = await this.prisma.user.findUnique({ where: { id: userId } });
    if (!user) {
      throw new Error('User not found.');
    }

    const trades = await this.prisma.tradeRecord.findMany({
      where: { userId }
    });

    const workbook = new ExcelJS.Workbook();
    const worksheet = workbook.addWorksheet('Laporan Bulanan TBS');

    // 1. Title & Metadata Header
    worksheet.mergeCells('A1:G1');
    const titleCell = worksheet.getCell('A1');
    titleCell.value = 'FOREX BOT AI - INSTITUTIONAL PERFORMANCE REPORT';
    titleCell.font = { name: 'Arial', size: 14, bold: true, color: { argb: 'FFFFFFFF' } };
    titleCell.alignment = { vertical: 'middle', horizontal: 'center' };
    titleCell.fill = {
      type: 'pattern',
      pattern: 'solid',
      fgColor: { argb: 'FF008080' } // Teal brand color
    };

    worksheet.addRow([]); // Blank row
    worksheet.addRow(['Generated By:', user.email]);
    worksheet.addRow(['Report Date:', new Date().toLocaleString()]);
    worksheet.addRow(['Total Trades:', trades.length]);
    worksheet.addRow([]); // Blank row

    // 2. Table Headers
    const headers = ['Trade ID', 'Currency Pair', 'Type', 'Lot Size', 'Entry Price', 'Close Price', 'SPB Estate Volume'];
    worksheet.addRow(headers);
    
    // Style headers row
    const headerRow = worksheet.getRow(7);
    headerRow.font = { bold: true, color: { argb: 'FFFFFFFF' } };
    headerRow.eachCell((cell) => {
      cell.fill = {
        type: 'pattern',
        pattern: 'solid',
        fgColor: { argb: 'FF333333' }
      };
      cell.alignment = { horizontal: 'center' };
    });

    // 3. Add Data Rows
    trades.forEach((trade) => {
      worksheet.addRow([
        trade.id.substring(0, 8),
        trade.currencyPair,
        trade.tradeType,
        trade.lotSize,
        trade.entryPrice,
        trade.closePrice || 'OPEN',
        trade.spbEstate || 0.0 // Custom field for Laporan Bulanan TBS Mill vs Estate
      ]);
    });

    // Style data cells
    worksheet.eachRow((row, rowNumber) => {
      if (rowNumber > 7 && rowNumber <= 7 + trades.length) {
        row.eachCell((cell, colNumber) => {
          cell.border = {
            top: { style: 'thin', color: { argb: 'FFDDDDDD' } },
            bottom: { style: 'thin', color: { argb: 'FFDDDDDD' } },
            left: { style: 'thin', color: { argb: 'FFDDDDDD' } },
            right: { style: 'thin', color: { argb: 'FFDDDDDD' } }
          };
          if (colNumber === 3) {
            // Highlight BUY (green) vs SELL (red)
            cell.font = {
              bold: true,
              color: { argb: cell.value === 'BUY' ? 'FF10B981' : 'FFEF4444' }
            };
          }
        });
      }
    });

    // Set column widths
    worksheet.columns = [
      { width: 15 }, // ID
      { width: 15 }, // Pair
      { width: 12 }, // Type
      { width: 12 }, // Lot
      { width: 15 }, // Entry
      { width: 15 }, // Close
      { width: 22 }  // SPB Estate
    ];

    // 4. Auditor Signatures at the bottom
    const startSignRow = 10 + trades.length;
    worksheet.getCell(`A${startSignRow}`).value = 'AUDITED & VERIFIED BY:';
    worksheet.getCell(`A${startSignRow}`).font = { bold: true };
    
    worksheet.getCell(`A${startSignRow + 3}`).value = '___________________________';
    worksheet.getCell(`A${startSignRow + 4}`).value = 'Compliance Officer';
    worksheet.getCell(`A${startSignRow + 4}`).font = { italic: true };

    worksheet.getCell(`D${startSignRow + 3}`).value = '___________________________';
    worksheet.getCell(`D${startSignRow + 4}`).value = 'Internal IT Auditor';
    worksheet.getCell(`D${startSignRow + 4}`).font = { italic: true };

    // Set response headers for file download
    res.setHeader(
      'Content-Type',
      'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
    );
    res.setHeader(
      'Content-Disposition',
      `attachment; filename=Institutional_Report_${Date.now()}.xlsx`
    );

    // Write to response stream
    await workbook.xlsx.write(res);
    res.end();
  }
}
